package com.lukefitness.lukegymbackend.dao;

import com.lukefitness.lukegymbackend.models.TraineeHealthMetric;

import java.util.List;

public interface TraineeHealthMetricDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trainee_health_metrics
     *
     * @mbg.generated Wed Jul 12 19:28:51 ACST 2023
     */
    int deleteByPrimaryKey(Integer traineeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trainee_health_metrics
     *
     * @mbg.generated Wed Jul 12 19:28:51 ACST 2023
     */
    int insert(TraineeHealthMetric row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trainee_health_metrics
     *
     * @mbg.generated Wed Jul 12 19:28:51 ACST 2023
     */
    TraineeHealthMetric selectByPrimaryKey(Integer traineeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trainee_health_metrics
     *
     * @mbg.generated Wed Jul 12 19:28:51 ACST 2023
     */
    List<TraineeHealthMetric> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trainee_health_metrics
     *
     * @mbg.generated Wed Jul 12 19:28:51 ACST 2023
     */
    int updateByPrimaryKey(TraineeHealthMetric row);
}